version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3003:3003"
    command: bundle exec rails s -p 3003 -b '0.0.0.0'
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    container_name: federation-review-ruby-2.3
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    image: mariadb:10.4.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "13308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    container_name: federation-review-db-2.3

volumes:
  bundle:
  mysql_data:
